---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xapigateways.javaland.cloud.platform.api
spec:
  group: javaland.cloud.platform.api
  names:
    kind: XApiGateway
    plural: xapigateways
  claimNames:
    kind: ApiGateway
    plural: apigateways
  enforcedCompositionRef:
    name: xapigateways.javaland.cloud.platform.api
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              service:
                type: object
                properties:
                  name: 
                    type: string
                    description: Name of the targeted service. This will set the API Mapping Key for the domain names and is used in naming conventions
                  stage:
                    type: string
                    description: "Name of the Stage. This can be one of the following values: dev, qa, prod"
                required:
                - name
                - stage
              logging:
                type: object
                properties:
                  rentention: 
                    type: integer
                    default: 30
                  format:
                    type: string
                    default: "{\"requestId\":\"$context.requestId\",\"ip\":\"$context.identity.sourceIp\",\"caller\":\"$context.identity.caller\",\"user\":\"$context.identity.user\",\"requestTime\":\"$context.requestTime\",\"httpMethod\":\"$context.httpMethod\",\"resourcePath\":\"$context.resourcePath\",\"status\":\"$context.status\",\"protocol\":\"$context.protocol\",\"responseLength\":\"$context.responseLength\"}"
              parameters:
                type: object
                properties:
                  region:
                    type: string
                    default: eu-central-1
                  protocol:
                    type: string
                    default: HTTP
                  autoDeploy:
                    type: boolean
                    default: false
                  domainName:
                    type: string
                    description: Domain Name for public access
                  albName:
                    type: string
                    description: Name of ALB
                  clusterName:
                    type: string
                    description: Name of EKS Cluster
            required:
            - service
            - parameters
          status:
            type: object
            properties:
              account:
                type: string
              apiID:
                description: ID of deployed API Gateway
                type: string
              integrationID:
                description: ID of API Integration
                type: string
              listenerARN:
                description: ARN of ALB listener
                type: string
              vpcLinkID:
                description: ID of VPC Link
                type: string
    additionalPrinterColumns:
    - name: ApiID
      type: string
      jsonPath: ".status.apiID"